### PR TITLE
Refactoring the rules somewhat

### PR DESCRIPTION
**Pull request by larsvilhuber**
This probably breaks the scripts, they are not debugged.
An additional column appears that allows for alternates (for a given item/subitem). This should be used as a selector in the pattern, eg. restud.csv, but it could also be used in a selector app to enforce that one of a set of alternates is chosen.

### CODE REVIEW

**Review by korenmiklos — COMMENTED** [review]
I understand alternatives 1 and 2 are either/or. But what if there are more alternatives? Pick one? Let's think about how to code this up in a way that's clear to authors.

**Comment by korenmiklos** [comment]
Merging into a separate branch for experimentation.

**Comment by korenmiklos** [comment]
@larsvilhuber please see this word document. It looks quite confusing to me. I understand journals could pick one of the alternatives, but I want the main document to be clear to authors, not journal editors.

I would eliminate small differences in policy stance (like 12c), and come up with a different representation for policy alternatives. Add a separate column listing journal specific options (like 12a or 15)?

**Comment by korenmiklos** [comment]
https://github.com/REStud/guidance/blob/03be441229e6bb3b8f554dc4e68aabb043ae376e/RRS/Reproducible-Research-Standard-1.0.docx

**Comment by larsvilhuber** [comment]
Miklós,

I may have misunderstood your intent. The basic document is a list of all POSSIBLE clauses. A journal then tags them as "required", "suggested", "verified", or "not applicable". Not applicable ones can be filtered out. The journal-specific version is then the checklist that the author sees.

As a "Reproducible Research Standard" to be directly provided to the author (by whom?) it does not make a lot of sense to me. It must​ bear a relation to a specific journal's policy, and yet be such that it can be compared across journals.

So the flow I saw was:

  *   rule.csv : general purpose template (the "standard"(s))
  *   rule.csv -> restud.csv = Reproducibile-Research-Standard-1.0-restud.md filters it to become the "Standard (ReStud)" or as I see it, "self-certification by ReStud for compliance with the Standard"
  *   Reproducibile-Research-Standard-1.0-restud.md + authors' package = checklist.

Alternatively, you can figure out from the Standard as it currently stands a small number of template Policies (Policy RRS-1, Policy RRS-2, ...) which has various configurations of "required", "verified", "suggested", in a spreadsheet like fashion. Corresponding to each is checklist version of it. ReStud states "we follow Policy RRS-1", and that's the checklist the author picks. If EJ also uses "Policy RRS-1", then the same checklist works there.

I do not see the author as a direct end-user of the document as it stands.

Lars

--
Lars Vilhuber, Economist
Cornell University / Labor Dynamics Institute/
  ILR School / Department of Economics
American Economic Association - Data Editor
J-PAL IDEA Initiative - Co-Chair
Journal of Privacy and Confidentiality - Managing Editor

***@***.*** | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ***@***.*** | +1.607-255-2744
________________________________

**Comment by korenmiklos** [comment]
Lars,

This looks like a great workflow indeed. But then how do we communicate to the author that this AER branded document is "the same" as the Restud branded document? Maybe having a reference and link to the Standard gives reassurance that this is something commonly used.

I am happy to work out a backend for journals (.csv -> .md -> .docx whatever workflow) so that journal policies can easily be created. We still need, however, a frontend to the standard (a nice looking .pdf or website) so if anyone checks to see what it is, they get a clear answer.

I wouldn't do Policy 1, 2, ... 6 because the differences are relatively small and this would create confusion. Let me think of a nice way of visually representing "either/or" and "pick one" choices.

As an alternative, we could limit rules to only include the commonly required elements and letting each journal add their own special requirements. For example, Rule (1) could read in the standard "Data are made publicly available in a manner specified by the journal." Then the journal policy could list the Rule and add details on Implementation "(1) Data are included in the replication package."

This is probably much simpler conceptually, but requires very careful wording of rules so that they are neither too general nor too specific.

Miklos

**Comment by korenmiklos** [comment]
@larsvilhuber I tried the verbal generalization alternative: https://github.com/REStud/guidance/blob/alternatives/RRS/rules.docx 

I removed all implementation details (like emailing the editor or explaining special hardware, long-running scripts) and reformulated rules to leave some discretion to journals. See an example:

https://github.com/REStud/guidance/blob/alternatives/RRS/implementation-sample.docx

**Comment by larsvilhuber** [comment]
This looks like a great workflow indeed. But then how do we communicate to the author that this AER branded document is "the same" as the Restud branded document? Maybe having a reference and link to the Standard gives reassurance that this is something commonly used.

Haven't had time to look at the sample, but just wanted to get at this point of "branding". My thought was that the AEA checklist is "co-branded" with RRS. So there's a RRS logo (say, on the left), and a AEA logo (say on the right). It links back to the general checklist website, which lists all possible policy elements. The rule to allow for co-branding is that you have to re-use the verbiage as-is (i.e., the AEA checklist is a true subset of the general checklist website), except where verbatim deviations are explicitly allowed (as you noted, this might be necessary). (Note that the constraint about "not modifying" applies only to the checklist, not the journal's actually posted policy).

So there is (technical words) a provenance chain from the general checklist to the specific checklist that is visible to the user.

The other part is the Policy 1, 2,... vs. Policy AEA, Policy EJ, etc. One of the goals of the checklist is to convey that the journal requirements are similar. For that, I would want to see that Element 2.a is the same across all journals, but Element 3.c is only used by some journals, say. That is easiest if we have Policy 1, 2, 3... rather than a much larger set of journal-specific policies. But another way might simply be to have a dynamic table on the website, that lists each journal that uses RRS and its checklist (so the website has to be the checklist-generator for each journal), and you can then compare individual journals, something like that. It's technically more challenging, but also more general.

Lars

--
Lars Vilhuber, Economist
Cornell University / Labor Dynamics Institute/
  ILR School / Department of Economics
American Economic Association - Data Editor
J-PAL IDEA Initiative - Co-Chair
Journal of Privacy and Confidentiality - Managing Editor

***@***.*** | http://lars.vilhuber.com/
p: +1.607-330-5743 | https://twitter.com/larsvil

Assistant: ***@***.*** | +1.607-255-2744
________________________________

**Pull request merged**
